Update logic, added functions bug fix
Tinggaard/P1 pull request #19
Opened 2022-11-18 09:58 UTC by Maxnm47

2022-11-18 21:49 UTC, Tinggaard commented
Skal lige se om det workflow kan virke

2022-11-18 21:49 UTC, Tinggaard commented
damn

2022-11-18 21:51 UTC, Tinggaard requested changes
Noget logik er forkert, koden compiler ikke ifølge CMake

2022-11-18 21:51 UTC, Tinggaard commented
https://github.com/Tinggaard/P1/actions/runs/3500472352/jobs/5863173623

2022-11-18 21:52 UTC, Maxnm47 commented
Thomas' funktion er heller ikke færdig
det er det jeg har lavet nu her, men har ikke kunne pushe fordi jeg fuckede mit git

2022-11-18 22:39 UTC, Maxnm47 commented
> Noget logik er forkert, koden compiler ikke ifølge CMake

work now, how i resolve change

2022-11-19 07:07 UTC, Tinggaard approved these changes

2022-11-19 14:57 UTC, merged