added function for sorting for cheapest overall store,
Tinggaard/P1 pull request #20
Opened 2022-11-19 16:06 UTC by Maxnm47

Co-authored by thomast2001@gmail.com
Co-Authored by maxnm47@gmail.com

2022-11-21 12:44 UTC, Maxnm47 commented
Lige nu ændre jeg bare værdierne inde i structet cart_item, måske skulle vi lave en kopi at det der kommer ind i cheapest_closet_store

2022-11-21 12:44 UTC, Maxnm47 commented
what do u guys think? ;)

2022-11-22 09:03 UTC, Tinggaard requested changes

2022-11-22 09:03 UTC, Tinggaard commented on CMakeLists.txt
> +
wat da fak

2022-11-22 09:03 UTC, Tinggaard commented on src/lib.c
> +
huh

2022-11-22 09:03 UTC, Tinggaard commented on src/lib.h
> +
væk

2022-11-22 09:03 UTC, Tinggaard commented on src/main.c
> +
huh

2022-11-22 09:08 UTC, Tinggaard approved these changes

2022-11-23 09:44 UTC, Tinggaard approved these changes

2022-11-23 09:45 UTC, merged