Calculates the shortest path across stores
Tinggaard/P1 pull request #33
Opened 2022-12-01 13:04 UTC by enevoldsen1oo

Co-authored-by: Jens <mail@t1ng.dk>
Co-authored-by: Mikkel <se38iz@student.aau.dk>
Ikke merge, den virker, men mangler småjusteringer

2022-12-01 13:06 UTC, Thomast2001 commented
gj, jeg merger nu

2022-12-01 16:02 UTC, MikkelBaekgaardJoergensen requested changes

2022-12-01 16:02 UTC, MikkelBaekgaardJoergensen commented on src/lib.c
> +    printf("Your absolute cheapest customized shopping list\n");
Der er noget logik her, som gør, at vi ikke kan printe forskellige varer fra samme butik. Så det skal vi lige have kigget på og fikset

2022-12-01 16:15 UTC, Tinggaard commented on src/lib.c
> +    printf("Your absolute cheapest customized shopping list\n");
Yes, vi har fundet ud af hvad det er, men skal lige have talt om det i morgen

2022-12-01 17:23 UTC, Maxnm47 commented on src/lib.c
> +        for (int j = 0; j < n_shopping_list; ++j) {
kunne vi ikke binary search her hvis vi sorter først?

2022-12-02 12:04 UTC, Maxnm47 approved these changes

2022-12-02 12:05 UTC, merged